# Generated by Django 2.0.2 on 2018-06-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180605_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id',
            new_name='note_id',
        ),
    ]
