# Generated by Django 2.0.2 on 2018-06-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20180605_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
